# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/cpp-pipeline/"
      - "/golang-pipeline/"
      - "/gradle-pipeline/"
      - "/maven-pipeline/"
      - "/node-pipeline/"
      - "/python-pipeline/"
      - "/python-poetry-pipeline/"
      - "/python-uv-pipeline/"
      - "/rust-pipeline/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directories:
      - "/cpp-pipeline/"
      - "/golang-pipeline/"
      - "/gradle-pipeline/"
      - "/maven-pipeline/"
      - "/node-pipeline/"
      - "/python-pipeline/"
      - "/python-poetry-pipeline/"
      - "/python-uv-pipeline/"
      - "/rust-pipeline/"
    schedule:
      interval: "weekly"