name: Golang CI Pipeline

on: [push]

env:
  DOCKER_IMAGE_NAME: ""
  PROJECT_DIR: "."
  GOLANG_VERSION: "1.23"
  GOLANG_DEPENDENCIES: ""
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
      packages: write
      actions: read
      security-events: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run Custom Golang CI action
      uses: ./.github/actions/golang
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        gitleaks_token: ${{ secrets.GITLEAKS_TOKEN }}       
        source_dir: ${{ env.PROJECT_DIR }}
        golang_version: ${{env.GOLANG_VERSION}}
        dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
        dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
        docker_image_name: ${{ env.DOCKER_IMAGE_NAME || github.event.repository.name }}
        golang_packages: ${{ env.GOLANG_DEPENDENCIES }}
        