name: Angular CI
description: 'Builds, tests, and deploys a Node.js Angular application'

inputs:
  github_token:
    description: 'Automatically created token. Set this to the GITHUB_TOKEN secret'
    required: true
  gitleaks_token:
    description: 'Organisational token for Gitleaks'
    required: false # only required for Organizations, not personal accounts
  node_version:
    description: 'Node Version'
  sonar_token:
    description: 'Token for SonarCloud access'
    required: true
  sonar_args:
    description: 'Custom SonarCloud arguments'
    required: true
  docker_image_name:
    description: 'Docker image name'
    required: true
  dockerhub_username:
    description: 'DockerHub username'
    required: true
  dockerhub_token:
    description: 'DockerHub token for authentication'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Validate conventional commits
      uses: wagoid/commitlint-github-action@v6    

    - name: Scan for secrets
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GITLEAKS_LICENSE: ${{ inputs.gitleaks_token }} 

    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Create test:ci
      run: npm pkg set scripts.test:ci="ng test --no-watch --no-progress --browsers=ChromeHeadless"
      shell: bash

    - name: Test Angular application (headless)
      run: npm run test:ci
      shell: bash

    - name: Sonarcloud SAST
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        SONAR_TOKEN: ${{ inputs.sonar_token }}
      with:
        args: ${{ inputs.sonar_args }}
